#!/bin/sh

TRACKPAD_DEV=13
SPEED_PROP=335

MIN_SPEED=2.0
MAX_SPEED=3.5
ACCELERATION=.3

FINGER_PROP=324
FINGER_LOW=32
FINGER_HIGH=37
FINGER_PRESS=0

xinput set-prop $TRACKPAD_DEV $SPEED_PROP $MIN_SPEED $MAX_SPEED $ACCELERATION 0
xinput set-prop $TRACKPAD_DEV $FINGER_PROP $FINGER_LOW $FINGER_LOW $FINGER_PRESS
